# site settings
title: MeritPoint Pathways
subtitle: Education & Career Pathways | Financial Guidance
email: info@meritpoint.ca
description: Free consultation for education planning, government funding & loans, and career pathways all over the world.<br />No upfront fees. Clear next steps.
baseurl: ""
url: "https://meritpoint.ca"
author: MeritPoint Pathways

street_address: 7205 Goreway Dr
city: Mississauga
state: ON
zip_code: L4T 0B4
country: Canada
phone: +1(437)-882-3664

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: instagram.com/meritpointpathways
  LinkedIn:
  Facebook:
  GitHub:
  Twitter:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
